La idea de esta práctica es ejercitar los puntos que vamos a necesitar para resolver el desafío.

Usaremos un resumen del dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data


## Ejercicio 1
Leer los datos del archivo /M1/CLASE_03_Numpy/Data/sales_data_sample_excercise.csv

Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres. 

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.

¿Qué pasaría si intentáramos crear una instancia de tipo int? ¿Y de tipo float?


In [2]:
import numpy as np

# local:
data_location = './Data/sales_data_sample_excercise.csv'

data = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= str)
data

array([['10107', '2871', '2', '2003', 'Motorcycles', 'USA'],
       ['10121', '2765.9', '5', '2003', 'Motorcycles', 'France'],
       ['10134', '3884.34', '7', '2003', 'Motorcycles', 'France'],
       ...,
       ['10386', '5417.57', '3', '2005', 'Ships', 'Spain'],
       ['10397', '2116.16', '3', '2005', 'Ships', 'France'],
       ['10414', '3079.44', '5', '2005', 'Ships', 'USA']], dtype='<U16')

# Ejercicio 2 - Tipos

Crear un array numérico que tenga como valores las columna SALES y otro array de str que tenga como valores la columna COUNTRY

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

In [3]:
sales_vector_str = data[:, 1]
sales_vector =  sales_vector_str.astype(np.float64)
print(sales_vector)

[2871.   2765.9  3884.34 ... 5417.57 2116.16 3079.44]


In [4]:
country_vector = data[:, 5]
print(country_vector)

['USA' 'France' 'France' ... 'Spain' 'France' 'USA']


## Ejercicio 3 - Funciones de agregación

Sobre los datos de precios de ventas (columna SALES) calcular:

* mínimo

* máximo

* promedio

* cantidad

* suma

Ayuda: https://docs.scipy.org/doc/numpy-1.17.0/reference/routines.statistics.html

In [5]:
np.amin(sales_vector) #Otra opción: sales_vector.min()

482.13

In [6]:
np.amax(sales_vector) #Otra opción: sales_vector.max()

14082.8

In [7]:
np.average(sales_vector)

3553.889071909316

In [8]:
sales_vector.size

2823

In [9]:
np.sum(sales_vector)

10032628.85

## Ejercicio 4 - Indexing

a) ¿Cuántas ventas se hicieron en USA?

Ayuda: boolean indexing

b) ¿Cuáles son los precios de las 5 ventas que están en las filas 6 a 10 del dataset?

Resolvamos usando array slicing y fancy indexing

Ayuda: recuerden `range` https://docs.python.org/3/library/functions.html#func-range

In [10]:
np.count_nonzero(country_vector == 'USA')
# otra opción
#mask = country_vector == 'USA'
#country_vector_USA = country_vector[mask]
#country_vector_USA.size

1004

In [11]:
# array slicing:
sales_vector[6:11]

array([2497.77, 5512.32, 2168.54, 4708.44, 3965.66])

In [12]:
# fancy indexing
indexes = range(6, 11, 1)
indexes_int = [6, 7, 8, 9, 10]
sales_vector_fancy = sales_vector[indexes_int]
print(sales_vector_fancy)

[2497.77 5512.32 2168.54 4708.44 3965.66]
