In [8]:
import numpy as np

In [9]:
mi_array = np.array([1,2,3,4,5,6,7])

In [10]:
solo_pares = mi_array % 2 == 0
print(solo_pares)

[False  True False  True False  True False]


In [11]:
mi_array[solo_pares]


array([2, 4, 6])

In [12]:
solo_mayores_5 = mi_array>5
mi_array[solo_mayores_5]

array([6, 7])

In [15]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [16]:
data = np.array([[0, 1, 2, 3, 4], 
              [2, 3, 5, 6, 7], 
              [5, 6, 7, 8, 9], 
              [10, 11, 12, 13, 14], 
              [15, 16, 17, 18, 19], 
              [1, 2, 3, 4, 5]
             ])
data

array([[ 0,  1,  2,  3,  4],
       [ 2,  3,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 1,  2,  3,  4,  5]])